language: node_js
node_js: 6.9.4
script: npm run release
before_deploy: zip -r video50.zip .
deploy:
  provider: elasticbeanstalk
  access_key_id: "$AWS_ACCESS_KEY_ID"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY"
  region: us-east-1
  app: video50
  env: video50
  bucket_name: travis50
  skip_cleanup: true
  zip_file: video50.zip
  on:
    branch: master
