language: node_js
node_js: 6.9.4
install:
  - mkdir public
  - npm install
script: npm run release
deploy:
  provider: elasticbeanstalk
  access_key_id: "$AWS_ACCESS_KEY_ID"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY"
  region: us-east-1
  app: video50
  env: video50
  bucket_name: travis50
  on:
    branch: master
